
name: debug
root: /root/test/Methods/CUDA/pixmatch_tm/
train: True
seed: 42
wandb: False
num_target: 2
data:

  num_classes: 18

  source:
    dataset: 'gta5'
    kwargs:
      root: /root/test/datasets/local_datasets/GTA5
      list_path: ${root}/datasets/gta5_list
      base_size: [1024, 512]
      crop_size: [1024, 512]
      random_mirror: True
      random_crop: False
      resize: True
      gaussian_blur: True
      class_16: False
      class_13: False

  target:
    dataset: 'IDD' #cityscapes or IDD or MapillaryVistas
    kwargs:
      root: /root/test/datasets/local_datasets/IDD
      list_path: ${root}/datasets/idd_list
      base_size: [1024, 512]
      crop_size: [1024, 512]
      random_mirror: True
      random_crop: False
      resize: True
      gaussian_blur: True
      class_16: False
      class_13: False
  target_memory:
    dataset: 'cityscapes' #cityscapes or IDD or MapillaryVistas
    kwargs:
      root: /root/test/datasets/local_datasets/CityScapes
      list_path: ${root}/datasets/city_list
      pseudo_path: ${root}/Pseudo/pseudo_city
      base_size: [1024, 512]
      crop_size: [1024, 512]
      random_mirror: True
      random_crop: False
      resize: True
      gaussian_blur: True
      class_16: False
      class_13: False
  loader:
    kwargs:
      batch_size: 2
      num_workers: 2
      pin_memory: True

  source_val_iterations: 100

model:
  backbone: deeplabv2_multi
  imagenet_pretrained: /data/shinahyung/code/3CUDA/SOURCE_ONLY/gta5_18class.pth
  checkpoint: "/root/test/Methods/CUDA/pixmatch_tm/pixmatch_TM_pretrained/best_pixTM_idd.pth"
  resume_from_checkpoint: True

opt:
  kind: "SGD"
  momentum: 0.9
  weight_decay: 5e-4
  lr: 1e-4
  iterations: 40000
  poly_power: 0.9
  learning_rate: 2.5e-4


# For auxiliary mode output
aux: True
lam_aux: 0.1
lam_new: 0.1
# Exponential weighted average of model parameters
ema_decay: 0.999

# Perturbations
pseudolabel_threshold: 0.0
lam_aug: 0.1
lam_fourier: 0.0
lam_cutmix: 0.0

# Fourier
source_fourier: False
fourier_beta: 0.01

